-- DBMS - Database Management System 
-- Manage Data: CRUD Operation
-- Ceate
-- Read
-- Update
-- Delete
-- sql - Structured Query Language 
-- DML - Data Modification Language
-- DDL - Data Definition Language
-- DCL - Data Control Language
-- TCL - Transaction Control Language
-- SQL is the language but the system we would be using is MySQL